[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[plugins]]
package = "netlify-plugin-is-website-vulnerable"

[[plugins]]
package = "netlify-plugin-inline-critical-css"

[[plugins]]
  # runs Cypress tests against the deployed URL
  package = "netlify-plugin-cypress"
