name: Run tests
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: YieldingExploiter/License-Action@1.0.1
        with:
          project-root: '.' # Root of the project, contains the package.json

      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: |
          yarn
          yarn lint
          yarn test
